config/routes.rb
Rails.application.routes.draw do
  root :to => 'images#index'

  resources :stories do
    resources :contributions
  end

  resources :images, :only => [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :story
  belongs_to :image
  validates :username, :presence => true
  validates :sentence, :presence => true, :length => {:maximum => 140}
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :contributions
  validates :image, :presence => true
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :contributions
  validates :title, :presence => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def new
    @image = Image.all.sample
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.new
  end

  def create
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.new(contribution_params)
    if @contribution.save
      flash[:notice] = "Thanks for your contribution!"
      redirect_to story_path(@contribution.story)
    else
      flash[:alert] = "Oops, please try again."
      @image = Image.find(contribution_params[:image_id])
      render :new
    end
  end

  def edit
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.find(params[:id])
    @image = Image.find(@contribution.image_id)
  end

  def update
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.find(params[:id])
    if @contribution.update(contribution_params)
      redirect_to story_path(@contribution.story)
    else
      render :edit
    end
  end

  def destroy
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    redirect_to story_path(@contribution.story)
  end

private
  def contribution_params
    params.require(:contribution).permit(:username, :sentence, :image_id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    if params[:title]
      @stories = Story.fuzzy_search(title: (params[:title]))
    else
    @stories = Story.order('title ASC, created_at DESC')
    end
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      flash[:notice] = "Story successfully created!"
      redirect_to stories_path
    else
      flash[:alert] = "Oops, please try again."
      render :new
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
    if @story.update(story_params)
      redirect_to stories_path
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

private
  def story_params
    params.require(:story).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contributions/_form.html.erb
<div class="col-xs-6">
  <%= form_for [@story, @contribution] do |f| %>
  <%= f.label :sentence %>
  <%= f.text_area :sentence, size: "15x4", :class => "form-control"%>
  <%= f.label :username %>
  <%= f.text_field :username, :class => "form-control"%>
  <%= f.hidden_field :image_id, :value => @image.id %>
  <%= f.submit :class => "btn btn-primary"%>
  <% end %>
</div>

app/views/contributions/edit.html.erb
<h1>Edit Your Contribution:</h1>
<h3> Your inspiration: <%= image_tag @image.image %></h3>
<%= render 'form' %>

app/views/contributions/new.html.erb
<h1>Add a sentence to <%= @story.title %> (Limited to 140 characters)</h1>
<h3>Here's your inspiration:</h3>
<%= image_tag @image.image %>
<%= render 'form' %>

app/views/images/index.html.erb
<h1 class="center">Click on an image to see what it has inspired!</h1>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <ul>
      <% @images.each do |image| %>
      <div class="col-xs-3"><%= link_to (image_tag image.image), image_path(image) %></div>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-xs-2 col-xs-offset-5">
    <%= link_to "New Story", new_story_path, :class => "btn btn-primary btn-block btn-lg" %>
  </div>
</div>

app/views/images/show.html.erb
<h1><%= image_tag @image.image %></h1>
<h3>Story contributions related to this image:</h3>
<% if @image.contributions.any? %>
  <ul>
    <% @image.contributions.each do |contribution| %>
    <li>
      <%= contribution.sentence %>
      <%= contribution.username %>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>This image has not been used in any stories yet!</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Story Time!</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
      <ul class="nav navbar-nav">
        <li><%= link_to "Stories", stories_path %></li>
        <li><%= link_to "New Story", new_story_path %></li>
        <li><%= link_to "Images", images_path %></li>
      </ul>
      </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="flash_alert">
        <%= flash[:alert] %>
      </div>
      <div class="flash_notice">
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stories/_form.html.erb
<div class="col-xs-6">
  <%= form_for @story do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :class => "form-control" %>
  <%= f.submit 'Submit', :class => "btn btn-primary"%>
  <% end %>
</div>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<%= render 'form' %>

app/views/stories/index.html.erb
<h1>Stories</h1>

<ul>
  <% @stories.each do |story| %>
    <li><%= link_to story.title, story_path(story) %>  (started <%= time_ago_in_words(story.created_at) %> ago)</li>
  <% end %>
</ul>

<p><%= link_to "Create a New Story", new_story_path %></p>
<p><%= link_to "View Inspiring Images", images_path %></p>

<div class="col-xs-6">
  <%= form_tag stories_path, :method => "get" do%>
  <p>
    <h4>Search for Stories:</h4>
    <%= text_field_tag :title, params[:title], :class => "form-control" %>
    <%= submit_tag "Search", :name => nil, :class => "btn btn-primary" %>
  </p>
  <% end %>
</div>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render "form" %>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>
<% if @story.contributions.any? %>
  <ul>
    <% @story.contributions.each do |contribution| %>
    <li>
      <%= contribution.sentence %>
      <%= contribution.username %>
      <%= image_tag contribution.image.image %>
      <%= link_to 'Edit Contribution', edit_story_contribution_path(@story, contribution) %>
      <%= link_to 'Delete Contribution', story_contribution_path(@story, contribution), :data => {:confirm => "Are you sure?", :method => "delete"} %><br>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>This story has not been written yet!</p>
<% end %>

<%= link_to 'Keep the story going!', new_story_contribution_path(@story) %><hr>

<%= link_to 'Edit Story Title', edit_story_path(@story) %><br>
<%= link_to 'Delete Story', story_path(@story), :data => {:confirm => "Are you sure?", :method => "delete"} %><br>

<%= link_to "Return to stories", stories_path %>